### ISSUE TITLE
Generator directly executes PATCH when loading

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/generator-solid-react#116]
When I visit https://dev-generator.inrupt.com/profile, it executes 3 `PATCH` requests without my consent:

```
INSERT DATA {
  <https://rubentest.solidtest.space/profile/card#me> <http://www.w3.org/2006/vcard/ns#hasEmail> <#id1552570920000>.
}
```

It sends those without authentication headers.

Furthermore, when those requests fail (for CORS reasons), then the app crashes.

**Comment by james-martin-jd** [comment]
This was resolved in 0.5.0 with the ShexFormBuilder integration. Previously we were making new namedNodes to store address in because we needed to tie to something or else the form didn't "know" there should be an address/email/etc. Now, the shape handles this for us and lets us know what should be there, even if the data isn't in the Pod yet.
