### ISSUE TITLE
huge `owl:equivalentClass` entry in my profile

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#176]
Hi! Not sure if this was caused by the sdk or by the data browser or by some other app, but there is a lot of `owl` data in my profile on dev.inrupt.net now (almost 500 lines, apparently?).

To reproduce:

```sh
curl -k https://michielbdejong.dev.inrupt.net/profile/card | grep owl | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 74154    0 74154    0     0  34330      0 --:--:--  0:00:02 --:--:-- 34346
     496
```

**Comment by michielbdejong** [comment]
ha, I think https://www.w3.org/2006/vcard/ns got copied into it! :)

**Comment by james-martin-jd** [comment]
I think this is unlikely to be caused by the SDK itself. If an entire vocab got copied over, that seems like it would be a bulk save or a SPARQL query gone wrong. We don't use SPARQL directly in the SDK, and LDFlex (which we use exclusively for read and writing, with only one exception) does not have a bulk insert. 

If you have steps to reproduce I'd be happy to test myself as well.

**Comment by michielbdejong** [comment]
yeah, i probably pasted it in myself by accident. thanks!

**Comment by jaxoncreed** [comment]
I saw that this happens when you modify your trusted apps via the trusted app pane specifically.

**Comment by michielbdejong** [comment]
oh well, if it's reproducable then we should open an issue on the solid-panes repo!

**Comment by megoth** [comment]
Just to note, the bug in trustedApplicationsPane was fixed in https://github.com/solid/solid-panes/pull/79
