### ISSUE TITLE
develop branch build issues

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#261]
On the current develop branch,
* [ ] npm audit finds a high severity security issue in jest
* [ ] jest does not seem to be correctly configured to understand .jsx, so 40 tests fail
* [ ] in the generated app, `npm install` fails because it requires the non-existing solid-forms package
* [ ] `npm start` opens https://localhost:3000 instead of http://localhost:3000

This makes the generator hard to contribute to. Can I help to fix these issues?

**Comment by michielbdejong** [comment]
A work-around for the https issue is to use `HTTP=true npm start`

**Comment by james-martin-jd** [comment]
Right now, develop is in a strange interim state due to the scope of work - we're using an internal nexus build to host works-in-progress prior to release. This should resolve itself as the process improves over the next few weeks.

I have not seen any tests fail, can you try grabbing latest and testing again? The noteworthy tests are in /generators/app/templates folder, not the tests on the root of the site (since it's a yeoman generator, the actual app tests are separate). The root test runner tries to pull all the tests in, but it's outside the context of React, so it fails. It may be worth it to remove the test script from the parent-most directory.
