### ISSUE TITLE
App should request the user for permissions to read, write, append, or control

### ISSUE THREAD

**Issue by jholleran** [inrupt/generator-solid-react#272]
**Is your feature request related to a problem? Please describe.**
When logging into an SDK generated app (with Solid IDP) but you have not set up the permissions to allow read, write, append, or control the app with display the following error:

![image](https://user-images.githubusercontent.com/1751613/69137505-d01a5880-0ab4-11ea-8393-7b60f6593aa5.png)

**Describe the solution you'd like**
Instead of displaying this error the app should request the user for the permissions it needs. It could use check boxes for read, write, append, or control permissions. It should also display a clear message to inform the user of what it needs this access for. When the user makes the selection it should send a PATCH request to update the Trusted Apps on the user Profile.

**Describe alternatives you've considered**
Currently in NSS it will request the user for the permissions but it doesn't seem to be the best place to have this functionality. Having it within the app would be a lot better as the app has more context of why it needs these permissions.

**Additional context**
Another nice to have would be if the user only selected read access then the app would still work but it would be in read only mode. So you would be able to read the Profile but not update it.

Also, the ability to change the permissions within the app.

**Comment by kevin-howard-jd** [comment]
The Generator could certainly handle the permissions errors better. In fact, we are currently reworking the permissions workflow to catch these kind of errors when attempting to use Tic-Tac-Toe. 

However, while I understand the proposal to make this app-level functionality, from a UX and security point of view, this seems problematic allowing a app to adjust permissions - it only takes one bad actor to adjust permissions without getting user permission to make the changes before faith in the user permissions model is lost.

I would propose that each server implements a standard API for an application to request permission changes. The app would call the API with the permission(s) it was requesting and text explaining why the permissions are needed. It is then up to the server to make the changes.

Additionally, I think having the permissions stored in the Profile is not a good idea long term, as anyone will be able to see the list of applications you have accessed (news, political, illegal, etc.) and the permissions you have to them.

**Comment by jholleran** [comment]
I get your point. This whole area looks like it needs to be looked into more.

BTW, from the error message above the permissions are `null` and the code is not handling it. Has this bug been fixed in the latest version? This should really display the popup message.

**Comment by kevin-howard-jd** [comment]
Agree on the first line.

With regards the 2nd line, the permissions workflow is being updated so that the permissions are be checked both when the application opens and also when the user accesses the Game page. And the workflow is being updated to be more pedantic, checking each required element of the game Pod structure - containers and files - exist just in case the structure is not created properly when the Game is first initiated potentially due to permissions issues. If a problem is found, an error toast will be displayed in the app.

**Comment by james-martin-jd** [comment]
@jholleran I'm currently reworking how the code works for permissions checks, so I will be sure to add a null handler so it doesn't blow up the page. It seems like that's what happens if you don't even give Read access. 

That being said, the user experience of the sample app will be very poor with no permissions, since profile won't load and will surely throw toast errors, even the welcome page will, and the notifications can't be read either.

In an earlier draft of the page we had a landing page for when there were no proper permissions (similar to how mobile apps work) but this was not implemented as the sample app actually pre-dates the trusted apps permissioning system.

**Comment by james-martin-jd** [comment]
The code as of 0.7.0 no longer assumes an empty array of permissions. You should now correctly see an error toast with a Learn More link.
