### ISSUE TITLE
QUESTION/POTENTIAL ISSUE

### ISSUE THREAD

**Issue by SharonStrats** [inrupt/generator-solid-react#307]
**Describe the bug**
When when to https://generator.inrupt.com/ it asked me to authorize the application.  I did not select the last un-ticked button to allow the app to grant/change access.  When the app came up it gave me a permissions error telling me to grant additional access.

**To Reproduce**
1. Go to https://generator.inrupt.com/  (key is to be a first time user)
2. Do not select any additional access and submit.
3. You will then see a notification about access.

**Expected behavior**
If the app needs the last access level selected I feel like it should already be selected for us, otherwise some sort of notice about the fact you need to select it to do... whatever it is we would get with the additional access.  

I was using Chrome.

**Additional context**
I did not try the tic tac toe game, but the profile editor still worked. I'm happy to test further if you don't already know about this.

**Comment by kevin-inrupt** [comment]
This is known behaviour. Unfortunately, as a developer you have no control over the Trusted Apps dialog that is displayed the first time you access a Pod from the Generator - the dialog is displayed by the server and the developer cannot adjust the displayed text or the selected items. So a bug in the Trusted Apps workflow, not the Generator.

The best that can currently be done is (as illustrated by the Generator) to catch the permissions error when it occurs, display an error and provide instructions for resolving the permissions issue. The Generator only requires Control permission when playing Tic-Tac-Toe so other functionality (Profile, Text Editor, Form Model Converter/Renderer) should work without issue.

While there are some band-aid solutions to the issue of providing an application with Control permission (even temporarily) to a Pod - the workflow outlined above, 3rd-party 'control' apps - the correct solution is that the application developer can send a request to the server with the set of permissions the application requires (in some cases it may only be read) and the reason for the required permissions. Then the displayed dialog can accurately set the permissions checkboxes and display the reason.

While it is unlikely that this will be fixed in the current Trusted Apps functionality, it should be a requirement of the Trusted Apps replacement currently in design.
